version: '3.8'
services:
    web:
        image: deyemsweek9
        build: .
        command: 'yarn start'
        ports:
            - '3000:3000'
        depends_on:
            - 'mongo'
    mongo:
        image: 'mongo'
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: me
            MONGO_INITDB_ROOT_PASSWORD: e5Px5NfyaqivEwt
