version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:12
            - image: circleci/mongo
        steps:
            - checkout
            - run:
                command: yarn
            - run:
                command: yarn tsc
            - run:
                command: yarn test
workflows:
    test-server:
        jobs:
            - build
                