version: 2.1

jobs:
    build:
        docker:
            - image: circleci/node:12
            - image: circleci/mongo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - dependency-cache-server-{{checksum "package.json"}}
                    - dependency-cache-server
            - run:
                command: yarn
            - run:
                command: yarn tsc
            - run:
                command: cp "../src/.env" "../dist/"
            - run:
                command: yarn test
workflows:
    test-server:
        jobs:
            - build
                